It's working
js-tasks-ru/jsbasic-20220901_borisnovikov4815 pull request #3
Opened 2022-09-12 17:23 UTC by BorisNovi

2022-09-12 17:24 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2022-09-12 19:07 UTC, SinimaWath requested changes

2022-09-12 19:07 UTC, SinimaWath commented on 2-module/1-task/index.js
> +      if (isNaN(salaries[key]) === true || isFinite(salaries[key]) === false) continue;
`isNaN(salaries[key]) === true || isFinite(salaries[key]) === false` - тут лишние проверки === true === false
Можно упростить до
`isNaN(salaries[key]) || !isFinite(salaries[key])`

2022-09-12 19:10 UTC, BorisNovi commented on 2-module/1-task/index.js
> +      if (isNaN(salaries[key]) === true || isFinite(salaries[key]) === false) continue;
Готово
Спасибо)

2022-09-12 19:11 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-09-12 19:56 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2022-09-13 16:14 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @SinimaWath

2022-09-13 16:55 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @SinimaWath

2022-09-14 09:18 UTC, SinimaWath requested changes

2022-09-14 09:18 UTC, SinimaWath commented on 3-module/1-task/index.js
> +let names = namify(users); // ['Вася', 'Петя', 'Маша']
убери из задач, все кроме функций

2022-09-14 11:54 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2022-09-14 12:00 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @SinimaWath

2022-09-14 12:01 UTC, BorisNovi commented on 3-module/1-task/index.js
> +let names = namify(users); // ['Вася', 'Петя', 'Маша']
Всё убрал

2022-09-14 17:20 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-09-14 17:26 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-09-14 17:29 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-09-14 17:52 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @SinimaWath

2022-09-14 18:10 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @SinimaWath

2022-09-14 18:22 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @SinimaWath

2022-09-14 18:22 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @SinimaWath

2022-09-14 18:31 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @SinimaWath

2022-09-14 18:31 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @SinimaWath

2022-09-14 18:31 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @SinimaWath

2022-09-15 15:23 UTC, SinimaWath requested changes

2022-09-15 15:23 UTC, SinimaWath commented on 3-module/4-task/index.js
> +  }
Давай переделаем на:
```
users
  .filter()
  .map()
  .join('\n')
```

2022-09-15 15:23 UTC, SinimaWath commented on 3-module/3-task/index.js
> +camelize('-webkit-transition') == 'WebkitTransition';
Убери из задач весь ненужный код кроме задач

2022-09-15 15:45 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2022-09-15 15:55 UTC, BorisNovi commented on 3-module/3-task/index.js
> +camelize('-webkit-transition') == 'WebkitTransition';
Готово

2022-09-15 16:14 UTC, BorisNovi commented on 3-module/4-task/index.js
> +  }
Сделано. Оказалось, так намного проще. Спасибо.

2022-09-15 16:14 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @SinimaWath

2022-09-16 17:06 UTC, SinimaWath approved these changes

2022-09-16 17:07 UTC, merged